### ISSUE TITLE
should we support ethermint in-process ?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/testnets#2]
I'm just worried about all the things users have to download and do to sync up ... obviously everything is easier for them if they only need one binary .

**Comment by melekes** [comment]
ethermint carrying tendermint onboard? we did that for basecoin. are there any downsides to doing the same for ethermint? licenses?

Another thing is upgrading process. Having a single binary would be beneficial comparing to two binaries.

**Comment by adrianbrink** [comment]
I think it is okay for basecoin since we control the flags and generally, there are not as many and they can be well in sync with tendermint.

For ethermint, on the other hand, the problem is that we have to manage two different sets of command line flags. Furthermore, go-ethereum uses urfave CLI while tendermint uses cobra, which means that we need to unify two different CLI systems.

Moreover, we should have at least one app where we dogfood the advertised split between tendermint core and the abci app since we are promising that in order to reduce complexity for other developers who want to build on top of tendermint.

Lastly (I am not a copyright expert), I think by running it in the same process we are walking along a fine edge since we are copying parts of the go-ethereum logic, uses it as a library and using tendermint as a library at the same time. I don't think we are breaking the copyright, but it gets very muddled up by running it in the same binary. Running it out-of-process gives it a very clear distinction.


From a usability perspective, I think we can have two approaches. 
The first one will be to have a very good README that clearly explains all the steps in a copy-and-paste style. That way users will only have to copy-and-paste one more command to run ethermint out-of-process.
Secondly, we could think about a solution where everything is packaged into one docker container and you can just install the docker container and ethermint will work and connect to the testnet.
Thirdly, I would love @melekes help on setting up ethermint to work with minikube, because then we can give users the possibility to run local testnets (not connecting to the main testnet) with one command, and maybe they could even connect all their nodes to the main testnet.

**Comment by zramsay** [comment]
https://github.com/tendermint/ethermint/issues/365
